### ISSUE TITLE
`arweave.transactions.getData()` failing

### ISSUE THREAD

**Issue by handlebauer** [textury/arlocal#63]
Using arlocal@1.1.18 on node@16.13.1:

```js
const arlocal = new ArLocal()
await arlocal.start()
```

When trying to fetch data using `arweave-js`...
```js
// Post transaction
await arweave.transactions.post(tx)

// Mine
await arweave.api.get('mine')

// Get data
await arweave.transactions.getData(tx.id) // <-- throws error
```
... arlocal throws:

```
{
  error: TypeError: Cannot read properties of undefined (reading 'offset')
      at null.<anonymous> (project/node_modules/arlocal/src/routes/transaction.ts:99:33)
      at Generator.next (<anonymous>)
      at fulfilled (project/node_modules/arlocal/bin/routes/transaction.js:5:58)
}
```

**Comment by fuadop** [comment]
Hey @handlebauer 👋, what type of file or transaction are you trying to upload?

**Comment by handlebauer** [comment]
> Hey @handlebauer 👋, what type of file or transaction are you trying to upload?

Hey @fuadop 😊,  just a plain string:

```js
const data = JSON.stringify({ hello: 'world' })
const transaction = await arweave.createTransaction({ data })

// note: the error persists regardless of whether the content type is specified in the tags

await arweave.transactions.sign(transaction, key)
await arweave.transactions.post(transaction)
```

I skimmed the arlocal code and debugged a little; I noticed [this line](https://github.com/textury/arlocal/blob/main/src/db/chunks.ts#L33) returns undefined when calling `getData()`:
```js
await this.connection('chunks').where({ data_root: dataRoot, data_size: dataSize })[0] // <-- returns undefined
```
Perhaps the chunks aren't being created in the first place?

**Comment by cedriking** [comment]
Are you using `arweave-js` or `blockweave`? If it's `arweave-js` then when you create the transaction it also requires the wallet. That might be the issue:

```ts
const data = JSON.stringify({ hello: 'world' })
const transaction = await arweave.createTransaction({ data }, key)

await arweave.transactions.sign(transaction, key)
await arweave.transactions.post(transaction)
```

You can read more about creating data transactions for arweave-js here: https://github.com/ArweaveTeam/arweave-js/#create-a-data-transaction

**Comment by handlebauer** [comment]
> when you create the transaction it also requires the wallet

No luck! Still having the same problem.

I replicated the issue here: https://github.com/handlebauer/arlocal-issue-63.

**Comment by cedriking** [comment]
@fuadop can you please test @handlebauer 's repo and take a deeper look into this. Thanks 👍🏼

**Comment by fuadop** [comment]
Okay @cedriking @handlebauer

**Comment by fuadop** [comment]
Hey @handlebauer , when this PR gets' merged and a new version is released, can you please update arlocal and re-test. Thanks 💪🏾

**Comment by handlebauer** [comment]
Hey guys, any word on this?

**Comment by cedriking** [comment]
Hey @handlebauer 👋🏼 , @kouraf is testing out an updated version. Can you please give it a try using the git branch https://github.com/textury/arlocal/tree/fix-chunks
```yarn add https://github.com/textury/arlocal.git#fix-chunks```

Best,
Cedrik

**Comment by cedriking** [comment]
Hey @handlebauer we have released `version 1.1.20` which solves this issue.

**Comment by muenchnair** [comment]
I tripple checked all my dependencies. I run arlocal version 1.1.20 and still experiencing this issue. Every time I try to retrieve data the offset error is thrown.

**Comment by diogosmendonca** [comment]
Hey Fellows, how are you? I'm experiencing the same problem described here. I'm using arlocal as a image of docker hub, in case, [textury/arlocal](https://hub.docker.com/r/textury/arlocal). I did a workaround to bypass the problem, but I actually want to remove it from the codebase. So, when this bug is fixed I'll. Follows the workaround that worked for me:

```
let data;
let buf;
if (arlocal){
     data = (await axios.get('http://' + config.arweave_host + ':' + 
                  config.arweave_port + '/tx/' +  txid + '/data')).data;
     buf = Buffer.from(data, 'base64');
}else{
     data = await arweave.transactions.getData(txid, {decode: true});
     buf = Buffer.from(data);
}
```

**Comment by fuadop** [comment]
Hey @handlebauer @heiningair @diogosmendonca , I think this work around should help you move on for the main time:

create a file , for a custom post function, `post.ts` or `post.js`:

```js
// tx is instance of a Transaction 
// arweave is your arweave instance
module.exports.post = async (tx, arweave) => {
  // custom upload function to bypass arlocal and arweave-js issue
  const MAX_CHUNKS_IN_BODY = 1;
  const chunksCount = tx.chunks.chunks.length;
  let isComplete = false

  // if chunksCount is greater than max_chunks_in_body
  // post the tx with no data
  // else post the tx with data 
  if (chunksCount <= MAX_CHUNKS_IN_BODY) {
    try {
      await arweave.api.post('tx', tx);
    } catch (e) {
      console.error(e)
    }
  } else {
    try {
      // empty the body
      tx.data = ''
      await arweave.api.post('tx', tx);
    } catch (e) {
      console.error(e)
    }
  }

  let chunkIndex = 0;
  while (!isComplete) {
    if (chunkIndex >= chunksCount) {
      isComplete = true
    } else {
      await arweave.api.post('chunk', tx.getChunk(chunkIndex, tx.data)) 
    }
    chunkIndex++
  }

  return isComplete;
};
```


You can then use this `post` function instead of  `arwave.transactions.post`:

```js
const Arweave = require('arweave');
const fs = require('fs');
const { post } = require('./post');

const arweave = Arweave.init({
  host: 'localhost',
  port: 1984,
  protocol: 'http'
});

(async () => {
  const key = await JSON.parse(fs.readFileSync('/home/fuad/Downloads/arweave-key-AJi5WQmN5iwVORrzjAv00Yau0OoF2npNsC0-xj2uWaQ.json'));

  const data = JSON.stringify({ hello: 'world' })
  // const file = fs.readFileSync('/home/fuad/Downloads/app-logo-1.png')
  const tx = await arweave.createTransaction({ data })

  await arweave.transactions.sign(tx, key);

  await post(tx, arweave);

  // now get your rawdata
  const rData = await arweave.transactions.getData(tx.id);
  console.log(rData);
})();

```

Be sure to fund your wallet with the `/mint/<address>/<amount_In_winstons>` endpoint, in order for your transaction to go through.

__NOTE: I am using node and commonjs , that's why I used `module.exports` and also `require`, use the appropriate equivalents for your env.__

**Comment by ppedziwiatr** [comment]
Hey, I've upgraded today our Contracts SDK to latest arlocal and arweave.js version and all out integration tests have exploded...I'm getting this "offset" error, that we've discussed some time ago on discord - https://discord.com/channels/357957786904166400/756557551234973696/930109683212116028

To reproduce:
1. clone `https://github.com/redstone-finance/redstone-smartcontracts`
2. update arlocal and arweave.js in package.json to latest versions
3. `yarn install`
4. `yarn test:integration`
